sudo: required
language: node_js
node_js:
  - "6"

before_script:
  - npm install -g gulp
script: gulp


addons:
  artifacts:
    debug: true
    bucket: test-aws-bucket-appsmart
    s3_region: us-east-1
